version: '3'

services:
  fronted:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
  api:
    build: ./api
    restart: always
    ports:
      - "5555:5000"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"

volumes:
  mysql_data: